services:
  - type: web
    name: arbitrage-telegram-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: BOT_TOKEN
        fromEnvVar: BOT_TOKEN
      - key: CHAT_ID
        fromEnvVar: CHAT_ID
