services:
  - type: worker
    name: arbitrage-telegram-bot
    runtime: python
    buildCommand: ""
    startCommand: "python main.py"
    envVars:
      - key: BOT_TOKEN
        fromEnvVar: BOT_TOKEN
      - key: CHAT_ID
        fromEnvVar: CHAT_ID
