services:
  - type: web
    name: arbitrage-telegram-bot
    runtime: python
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    plan: free
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: CHAT_ID
        sync: false
    env: 
      - key: PORT
        value: 10000
